# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inari', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Antibiotics',
            new_name='Antibiotic',
        ),
        migrations.RenameModel(
            old_name='Boxes',
            new_name='Box',
        ),
        migrations.RenameModel(
            old_name='OrderSources',
            new_name='OrderSource',
        ),
        migrations.RenameModel(
            old_name='Plasmids',
            new_name='Plasmid',
        ),
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
        migrations.RenameModel(
            old_name='Racks',
            new_name='Rack',
        ),
        migrations.RenameModel(
            old_name='Shelves',
            new_name='Shelf',
        ),
        migrations.RenameModel(
            old_name='Usages',
            new_name='Usage',
        ),
    ]
